version: '3.8'

services:
  app:
    build: .
    image: music-api-app
    container_name: music-api-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
    env_file:
      - .env

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DBNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: